/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module LUT(clk, rst, in0, in1, in2, in3, input_combination, wr_en, f_sel, is_synced, out, out_ff);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire D;
  input clk;
  wire clk;
  wire \dmux_inst.ff_out ;
  wire \dmux_inst.is_synced ;
  wire \dmux_inst.out ;
  input [1:0] f_sel;
  wire [1:0] f_sel;
  wire [1:0] f_sel_reg;
  wire \ff_inst.D ;
  wire \ff_inst.clk ;
  wire \ff_inst.out_ff ;
  wire \ff_inst.rst ;
  wire [3:0] \ff_inst2.D ;
  wire \ff_inst2.clk ;
  wire [3:0] \ff_inst2.out_ff ;
  wire \ff_inst2.rst ;
  wire \ff_inst3.D ;
  wire \ff_inst3.clk ;
  wire \ff_inst3.out_ff ;
  wire \ff_inst3.rst ;
  wire [1:0] \ff_inst4.D ;
  wire \ff_inst4.clk ;
  wire [1:0] \ff_inst4.out_ff ;
  wire \ff_inst4.rst ;
  input in0;
  wire in0;
  input in1;
  wire in1;
  input in2;
  wire in2;
  input in3;
  wire in3;
  input [3:0] input_combination;
  wire [3:0] input_combination;
  wire [3:0] input_combination_reg;
  input is_synced;
  wire is_synced;
  wire is_synced_reg;
  wire [1:0] \mux_inst.f_sel ;
  output out;
  wire out;
  output out_ff;
  wire out_ff;
  wire \reg_inst.clk ;
  wire \reg_inst.genblk1[0].SH.clk ;
  wire \reg_inst.genblk1[0].SH.rst ;
  wire [3:0] \reg_inst.genblk1[0].SH.sel ;
  wire \reg_inst.genblk1[0].SH.serial_in ;
  wire [15:0] \reg_inst.genblk1[0].SH.sr ;
  wire \reg_inst.genblk1[0].SH.wr_en ;
  wire \reg_inst.genblk1[1].SH.clk ;
  wire \reg_inst.genblk1[1].SH.rst ;
  wire [3:0] \reg_inst.genblk1[1].SH.sel ;
  wire \reg_inst.genblk1[1].SH.serial_in ;
  wire [15:0] \reg_inst.genblk1[1].SH.sr ;
  wire \reg_inst.genblk1[1].SH.wr_en ;
  wire \reg_inst.genblk1[2].SH.clk ;
  wire \reg_inst.genblk1[2].SH.rst ;
  wire [3:0] \reg_inst.genblk1[2].SH.sel ;
  wire \reg_inst.genblk1[2].SH.serial_in ;
  wire [15:0] \reg_inst.genblk1[2].SH.sr ;
  wire \reg_inst.genblk1[2].SH.wr_en ;
  wire \reg_inst.genblk1[3].SH.clk ;
  wire \reg_inst.genblk1[3].SH.rst ;
  wire [3:0] \reg_inst.genblk1[3].SH.sel ;
  wire \reg_inst.genblk1[3].SH.serial_in ;
  wire [15:0] \reg_inst.genblk1[3].SH.sr ;
  wire \reg_inst.genblk1[3].SH.wr_en ;
  wire \reg_inst.in0 ;
  wire \reg_inst.in1 ;
  wire \reg_inst.in2 ;
  wire \reg_inst.in3 ;
  wire [3:0] \reg_inst.in_array ;
  wire [3:0] \reg_inst.input_combination ;
  wire \reg_inst.rst ;
  wire \reg_inst.wr_en ;
  input rst;
  wire rst;
  input wr_en;
  wire wr_en;
  sky130_fd_sc_hd__nor2_1 _095_ (
    .A(\ff_inst4.out_ff [1]),
    .B(\ff_inst4.out_ff [0]),
    .Y(_064_)
  );
  sky130_fd_sc_hd__mux4_2 _096_ (
    .A0(\reg_inst.genblk1[0].SH.sr [12]),
    .A1(\reg_inst.genblk1[0].SH.sr [13]),
    .A2(\reg_inst.genblk1[0].SH.sr [14]),
    .A3(\reg_inst.genblk1[0].SH.sr [15]),
    .S0(\ff_inst2.out_ff [0]),
    .S1(\ff_inst2.out_ff [1]),
    .X(_065_)
  );
  sky130_fd_sc_hd__mux4_2 _097_ (
    .A0(\reg_inst.genblk1[0].SH.sr [8]),
    .A1(\reg_inst.genblk1[0].SH.sr [9]),
    .A2(\reg_inst.genblk1[0].SH.sr [10]),
    .A3(\reg_inst.genblk1[0].SH.sr [11]),
    .S0(\ff_inst2.out_ff [0]),
    .S1(\ff_inst2.out_ff [1]),
    .X(_066_)
  );
  sky130_fd_sc_hd__mux4_2 _098_ (
    .A0(\reg_inst.genblk1[0].SH.sr [4]),
    .A1(\reg_inst.genblk1[0].SH.sr [5]),
    .A2(\reg_inst.genblk1[0].SH.sr [6]),
    .A3(\reg_inst.genblk1[0].SH.sr [7]),
    .S0(\ff_inst2.out_ff [0]),
    .S1(\ff_inst2.out_ff [1]),
    .X(_067_)
  );
  sky130_fd_sc_hd__mux4_2 _099_ (
    .A0(\reg_inst.genblk1[0].SH.sr [0]),
    .A1(\reg_inst.genblk1[0].SH.sr [2]),
    .A2(\reg_inst.genblk1[0].SH.sr [1]),
    .A3(\reg_inst.genblk1[0].SH.sr [3]),
    .S0(\ff_inst2.out_ff [1]),
    .S1(\ff_inst2.out_ff [0]),
    .X(_068_)
  );
  sky130_fd_sc_hd__mux4_2 _100_ (
    .A0(_068_),
    .A1(_067_),
    .A2(_066_),
    .A3(_065_),
    .S0(\ff_inst2.out_ff [2]),
    .S1(\ff_inst2.out_ff [3]),
    .X(_069_)
  );
  sky130_fd_sc_hd__nand2_1 _101_ (
    .A(_064_),
    .B(_069_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _102_ (
    .A(\ff_inst4.out_ff [1]),
    .SLEEP(\ff_inst4.out_ff [0]),
    .X(_071_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _103_ (
    .A(\ff_inst4.out_ff [0]),
    .SLEEP(\ff_inst4.out_ff [1]),
    .X(_072_)
  );
  sky130_fd_sc_hd__and2_0 _104_ (
    .A(\ff_inst4.out_ff [1]),
    .B(\ff_inst4.out_ff [0]),
    .X(_073_)
  );
  sky130_fd_sc_hd__a222oi_1 _105_ (
    .A1(\reg_inst.genblk1[2].SH.sr [14]),
    .A2(_071_),
    .B1(_072_),
    .B2(\reg_inst.genblk1[1].SH.sr [14]),
    .C1(_073_),
    .C2(\reg_inst.genblk1[3].SH.sr [14]),
    .Y(_074_)
  );
  sky130_fd_sc_hd__a222oi_1 _106_ (
    .A1(\reg_inst.genblk1[2].SH.sr [12]),
    .A2(_071_),
    .B1(_072_),
    .B2(\reg_inst.genblk1[1].SH.sr [12]),
    .C1(_073_),
    .C2(\reg_inst.genblk1[3].SH.sr [12]),
    .Y(_075_)
  );
  sky130_fd_sc_hd__a222oi_1 _107_ (
    .A1(\reg_inst.genblk1[2].SH.sr [10]),
    .A2(_071_),
    .B1(_072_),
    .B2(\reg_inst.genblk1[1].SH.sr [10]),
    .C1(_073_),
    .C2(\reg_inst.genblk1[3].SH.sr [10]),
    .Y(_076_)
  );
  sky130_fd_sc_hd__a222oi_1 _108_ (
    .A1(\reg_inst.genblk1[2].SH.sr [8]),
    .A2(_071_),
    .B1(_072_),
    .B2(\reg_inst.genblk1[1].SH.sr [8]),
    .C1(_073_),
    .C2(\reg_inst.genblk1[3].SH.sr [8]),
    .Y(_077_)
  );
  sky130_fd_sc_hd__a222oi_1 _109_ (
    .A1(\reg_inst.genblk1[2].SH.sr [6]),
    .A2(_071_),
    .B1(_072_),
    .B2(\reg_inst.genblk1[1].SH.sr [6]),
    .C1(_073_),
    .C2(\reg_inst.genblk1[3].SH.sr [6]),
    .Y(_078_)
  );
  sky130_fd_sc_hd__a222oi_1 _110_ (
    .A1(\reg_inst.genblk1[2].SH.sr [4]),
    .A2(_071_),
    .B1(_072_),
    .B2(\reg_inst.genblk1[1].SH.sr [4]),
    .C1(_073_),
    .C2(\reg_inst.genblk1[3].SH.sr [4]),
    .Y(_079_)
  );
  sky130_fd_sc_hd__a222oi_1 _111_ (
    .A1(\reg_inst.genblk1[2].SH.sr [2]),
    .A2(_071_),
    .B1(_072_),
    .B2(\reg_inst.genblk1[1].SH.sr [2]),
    .C1(_073_),
    .C2(\reg_inst.genblk1[3].SH.sr [2]),
    .Y(_080_)
  );
  sky130_fd_sc_hd__a222oi_1 _112_ (
    .A1(\reg_inst.genblk1[2].SH.sr [0]),
    .A2(_071_),
    .B1(_072_),
    .B2(\reg_inst.genblk1[1].SH.sr [0]),
    .C1(_073_),
    .C2(\reg_inst.genblk1[3].SH.sr [0]),
    .Y(_081_)
  );
  sky130_fd_sc_hd__a222oi_1 _113_ (
    .A1(\reg_inst.genblk1[2].SH.sr [13]),
    .A2(_071_),
    .B1(_072_),
    .B2(\reg_inst.genblk1[1].SH.sr [13]),
    .C1(_073_),
    .C2(\reg_inst.genblk1[3].SH.sr [13]),
    .Y(_082_)
  );
  sky130_fd_sc_hd__a222oi_1 _114_ (
    .A1(\reg_inst.genblk1[2].SH.sr [15]),
    .A2(_071_),
    .B1(_072_),
    .B2(\reg_inst.genblk1[1].SH.sr [15]),
    .C1(_073_),
    .C2(\reg_inst.genblk1[3].SH.sr [15]),
    .Y(_083_)
  );
  sky130_fd_sc_hd__a222oi_1 _115_ (
    .A1(\reg_inst.genblk1[2].SH.sr [9]),
    .A2(_071_),
    .B1(_072_),
    .B2(\reg_inst.genblk1[1].SH.sr [9]),
    .C1(_073_),
    .C2(\reg_inst.genblk1[3].SH.sr [9]),
    .Y(_084_)
  );
  sky130_fd_sc_hd__a222oi_1 _116_ (
    .A1(\reg_inst.genblk1[2].SH.sr [11]),
    .A2(_071_),
    .B1(_072_),
    .B2(\reg_inst.genblk1[1].SH.sr [11]),
    .C1(_073_),
    .C2(\reg_inst.genblk1[3].SH.sr [11]),
    .Y(_085_)
  );
  sky130_fd_sc_hd__a222oi_1 _117_ (
    .A1(\reg_inst.genblk1[2].SH.sr [5]),
    .A2(_071_),
    .B1(_072_),
    .B2(\reg_inst.genblk1[1].SH.sr [5]),
    .C1(_073_),
    .C2(\reg_inst.genblk1[3].SH.sr [5]),
    .Y(_086_)
  );
  sky130_fd_sc_hd__a222oi_1 _118_ (
    .A1(\reg_inst.genblk1[2].SH.sr [7]),
    .A2(_071_),
    .B1(_072_),
    .B2(\reg_inst.genblk1[1].SH.sr [7]),
    .C1(_073_),
    .C2(\reg_inst.genblk1[3].SH.sr [7]),
    .Y(_087_)
  );
  sky130_fd_sc_hd__a222oi_1 _119_ (
    .A1(\reg_inst.genblk1[2].SH.sr [1]),
    .A2(_071_),
    .B1(_072_),
    .B2(\reg_inst.genblk1[1].SH.sr [1]),
    .C1(_073_),
    .C2(\reg_inst.genblk1[3].SH.sr [1]),
    .Y(_088_)
  );
  sky130_fd_sc_hd__a222oi_1 _120_ (
    .A1(\reg_inst.genblk1[2].SH.sr [3]),
    .A2(_071_),
    .B1(_072_),
    .B2(\reg_inst.genblk1[1].SH.sr [3]),
    .C1(_073_),
    .C2(\reg_inst.genblk1[3].SH.sr [3]),
    .Y(_089_)
  );
  sky130_fd_sc_hd__mux4_2 _121_ (
    .A0(_077_),
    .A1(_084_),
    .A2(_076_),
    .A3(_085_),
    .S0(\ff_inst2.out_ff [0]),
    .S1(\ff_inst2.out_ff [1]),
    .X(_090_)
  );
  sky130_fd_sc_hd__mux4_2 _122_ (
    .A0(_075_),
    .A1(_082_),
    .A2(_074_),
    .A3(_083_),
    .S0(\ff_inst2.out_ff [0]),
    .S1(\ff_inst2.out_ff [1]),
    .X(_091_)
  );
  sky130_fd_sc_hd__mux4_2 _123_ (
    .A0(_079_),
    .A1(_086_),
    .A2(_078_),
    .A3(_087_),
    .S0(\ff_inst2.out_ff [0]),
    .S1(\ff_inst2.out_ff [1]),
    .X(_092_)
  );
  sky130_fd_sc_hd__mux4_2 _124_ (
    .A0(_081_),
    .A1(_088_),
    .A2(_080_),
    .A3(_089_),
    .S0(\ff_inst2.out_ff [0]),
    .S1(\ff_inst2.out_ff [1]),
    .X(_093_)
  );
  sky130_fd_sc_hd__mux4_2 _125_ (
    .A0(_093_),
    .A1(_092_),
    .A2(_090_),
    .A3(_091_),
    .S0(\ff_inst2.out_ff [2]),
    .S1(\ff_inst2.out_ff [3]),
    .X(_094_)
  );
  sky130_fd_sc_hd__a21oi_1 _126_ (
    .A1(_070_),
    .A2(_094_),
    .B1(\ff_inst3.out_ff ),
    .Y(out)
  );
  sky130_fd_sc_hd__a21boi_0 _127_ (
    .A1(_070_),
    .A2(_094_),
    .B1_N(\ff_inst3.out_ff ),
    .Y(\dmux_inst.ff_out )
  );
  sky130_fd_sc_hd__mux2_1 _128_ (
    .A0(\reg_inst.genblk1[2].SH.sr [0]),
    .A1(in2),
    .S(wr_en),
    .X(_000_)
  );
  sky130_fd_sc_hd__mux2_1 _129_ (
    .A0(\reg_inst.genblk1[2].SH.sr [1]),
    .A1(\reg_inst.genblk1[2].SH.sr [0]),
    .S(wr_en),
    .X(_001_)
  );
  sky130_fd_sc_hd__mux2_1 _130_ (
    .A0(\reg_inst.genblk1[2].SH.sr [2]),
    .A1(\reg_inst.genblk1[2].SH.sr [1]),
    .S(wr_en),
    .X(_002_)
  );
  sky130_fd_sc_hd__mux2_1 _131_ (
    .A0(\reg_inst.genblk1[2].SH.sr [3]),
    .A1(\reg_inst.genblk1[2].SH.sr [2]),
    .S(wr_en),
    .X(_003_)
  );
  sky130_fd_sc_hd__mux2_1 _132_ (
    .A0(\reg_inst.genblk1[2].SH.sr [4]),
    .A1(\reg_inst.genblk1[2].SH.sr [3]),
    .S(wr_en),
    .X(_004_)
  );
  sky130_fd_sc_hd__mux2_1 _133_ (
    .A0(\reg_inst.genblk1[2].SH.sr [5]),
    .A1(\reg_inst.genblk1[2].SH.sr [4]),
    .S(wr_en),
    .X(_005_)
  );
  sky130_fd_sc_hd__mux2_1 _134_ (
    .A0(\reg_inst.genblk1[2].SH.sr [6]),
    .A1(\reg_inst.genblk1[2].SH.sr [5]),
    .S(wr_en),
    .X(_006_)
  );
  sky130_fd_sc_hd__mux2_1 _135_ (
    .A0(\reg_inst.genblk1[2].SH.sr [7]),
    .A1(\reg_inst.genblk1[2].SH.sr [6]),
    .S(wr_en),
    .X(_007_)
  );
  sky130_fd_sc_hd__mux2_1 _136_ (
    .A0(\reg_inst.genblk1[2].SH.sr [8]),
    .A1(\reg_inst.genblk1[2].SH.sr [7]),
    .S(wr_en),
    .X(_008_)
  );
  sky130_fd_sc_hd__mux2_1 _137_ (
    .A0(\reg_inst.genblk1[2].SH.sr [9]),
    .A1(\reg_inst.genblk1[2].SH.sr [8]),
    .S(wr_en),
    .X(_009_)
  );
  sky130_fd_sc_hd__mux2_1 _138_ (
    .A0(\reg_inst.genblk1[2].SH.sr [10]),
    .A1(\reg_inst.genblk1[2].SH.sr [9]),
    .S(wr_en),
    .X(_010_)
  );
  sky130_fd_sc_hd__mux2_1 _139_ (
    .A0(\reg_inst.genblk1[2].SH.sr [11]),
    .A1(\reg_inst.genblk1[2].SH.sr [10]),
    .S(wr_en),
    .X(_011_)
  );
  sky130_fd_sc_hd__mux2_1 _140_ (
    .A0(\reg_inst.genblk1[2].SH.sr [12]),
    .A1(\reg_inst.genblk1[2].SH.sr [11]),
    .S(wr_en),
    .X(_012_)
  );
  sky130_fd_sc_hd__mux2_1 _141_ (
    .A0(\reg_inst.genblk1[2].SH.sr [13]),
    .A1(\reg_inst.genblk1[2].SH.sr [12]),
    .S(wr_en),
    .X(_013_)
  );
  sky130_fd_sc_hd__mux2_1 _142_ (
    .A0(\reg_inst.genblk1[2].SH.sr [14]),
    .A1(\reg_inst.genblk1[2].SH.sr [13]),
    .S(wr_en),
    .X(_014_)
  );
  sky130_fd_sc_hd__mux2_1 _143_ (
    .A0(\reg_inst.genblk1[2].SH.sr [15]),
    .A1(\reg_inst.genblk1[2].SH.sr [14]),
    .S(wr_en),
    .X(_015_)
  );
  sky130_fd_sc_hd__mux2_1 _144_ (
    .A0(\reg_inst.genblk1[1].SH.sr [0]),
    .A1(in1),
    .S(wr_en),
    .X(_016_)
  );
  sky130_fd_sc_hd__mux2_1 _145_ (
    .A0(\reg_inst.genblk1[1].SH.sr [1]),
    .A1(\reg_inst.genblk1[1].SH.sr [0]),
    .S(wr_en),
    .X(_017_)
  );
  sky130_fd_sc_hd__mux2_1 _146_ (
    .A0(\reg_inst.genblk1[1].SH.sr [2]),
    .A1(\reg_inst.genblk1[1].SH.sr [1]),
    .S(wr_en),
    .X(_018_)
  );
  sky130_fd_sc_hd__mux2_1 _147_ (
    .A0(\reg_inst.genblk1[1].SH.sr [3]),
    .A1(\reg_inst.genblk1[1].SH.sr [2]),
    .S(wr_en),
    .X(_019_)
  );
  sky130_fd_sc_hd__mux2_1 _148_ (
    .A0(\reg_inst.genblk1[1].SH.sr [4]),
    .A1(\reg_inst.genblk1[1].SH.sr [3]),
    .S(wr_en),
    .X(_020_)
  );
  sky130_fd_sc_hd__mux2_1 _149_ (
    .A0(\reg_inst.genblk1[1].SH.sr [5]),
    .A1(\reg_inst.genblk1[1].SH.sr [4]),
    .S(wr_en),
    .X(_021_)
  );
  sky130_fd_sc_hd__mux2_1 _150_ (
    .A0(\reg_inst.genblk1[1].SH.sr [6]),
    .A1(\reg_inst.genblk1[1].SH.sr [5]),
    .S(wr_en),
    .X(_022_)
  );
  sky130_fd_sc_hd__mux2_1 _151_ (
    .A0(\reg_inst.genblk1[1].SH.sr [7]),
    .A1(\reg_inst.genblk1[1].SH.sr [6]),
    .S(wr_en),
    .X(_023_)
  );
  sky130_fd_sc_hd__mux2_1 _152_ (
    .A0(\reg_inst.genblk1[1].SH.sr [8]),
    .A1(\reg_inst.genblk1[1].SH.sr [7]),
    .S(wr_en),
    .X(_024_)
  );
  sky130_fd_sc_hd__mux2_1 _153_ (
    .A0(\reg_inst.genblk1[1].SH.sr [9]),
    .A1(\reg_inst.genblk1[1].SH.sr [8]),
    .S(wr_en),
    .X(_025_)
  );
  sky130_fd_sc_hd__mux2_1 _154_ (
    .A0(\reg_inst.genblk1[1].SH.sr [10]),
    .A1(\reg_inst.genblk1[1].SH.sr [9]),
    .S(wr_en),
    .X(_026_)
  );
  sky130_fd_sc_hd__mux2_1 _155_ (
    .A0(\reg_inst.genblk1[1].SH.sr [11]),
    .A1(\reg_inst.genblk1[1].SH.sr [10]),
    .S(wr_en),
    .X(_027_)
  );
  sky130_fd_sc_hd__mux2_1 _156_ (
    .A0(\reg_inst.genblk1[1].SH.sr [12]),
    .A1(\reg_inst.genblk1[1].SH.sr [11]),
    .S(wr_en),
    .X(_028_)
  );
  sky130_fd_sc_hd__mux2_1 _157_ (
    .A0(\reg_inst.genblk1[1].SH.sr [13]),
    .A1(\reg_inst.genblk1[1].SH.sr [12]),
    .S(wr_en),
    .X(_029_)
  );
  sky130_fd_sc_hd__mux2_1 _158_ (
    .A0(\reg_inst.genblk1[1].SH.sr [14]),
    .A1(\reg_inst.genblk1[1].SH.sr [13]),
    .S(wr_en),
    .X(_030_)
  );
  sky130_fd_sc_hd__mux2_1 _159_ (
    .A0(\reg_inst.genblk1[1].SH.sr [15]),
    .A1(\reg_inst.genblk1[1].SH.sr [14]),
    .S(wr_en),
    .X(_031_)
  );
  sky130_fd_sc_hd__mux2_1 _160_ (
    .A0(\reg_inst.genblk1[3].SH.sr [0]),
    .A1(in3),
    .S(wr_en),
    .X(_032_)
  );
  sky130_fd_sc_hd__mux2_1 _161_ (
    .A0(\reg_inst.genblk1[3].SH.sr [1]),
    .A1(\reg_inst.genblk1[3].SH.sr [0]),
    .S(wr_en),
    .X(_033_)
  );
  sky130_fd_sc_hd__mux2_1 _162_ (
    .A0(\reg_inst.genblk1[3].SH.sr [2]),
    .A1(\reg_inst.genblk1[3].SH.sr [1]),
    .S(wr_en),
    .X(_034_)
  );
  sky130_fd_sc_hd__mux2_1 _163_ (
    .A0(\reg_inst.genblk1[3].SH.sr [3]),
    .A1(\reg_inst.genblk1[3].SH.sr [2]),
    .S(wr_en),
    .X(_035_)
  );
  sky130_fd_sc_hd__mux2_1 _164_ (
    .A0(\reg_inst.genblk1[3].SH.sr [4]),
    .A1(\reg_inst.genblk1[3].SH.sr [3]),
    .S(wr_en),
    .X(_036_)
  );
  sky130_fd_sc_hd__mux2_1 _165_ (
    .A0(\reg_inst.genblk1[3].SH.sr [5]),
    .A1(\reg_inst.genblk1[3].SH.sr [4]),
    .S(wr_en),
    .X(_037_)
  );
  sky130_fd_sc_hd__mux2_1 _166_ (
    .A0(\reg_inst.genblk1[3].SH.sr [6]),
    .A1(\reg_inst.genblk1[3].SH.sr [5]),
    .S(wr_en),
    .X(_038_)
  );
  sky130_fd_sc_hd__mux2_1 _167_ (
    .A0(\reg_inst.genblk1[3].SH.sr [7]),
    .A1(\reg_inst.genblk1[3].SH.sr [6]),
    .S(wr_en),
    .X(_039_)
  );
  sky130_fd_sc_hd__mux2_1 _168_ (
    .A0(\reg_inst.genblk1[3].SH.sr [8]),
    .A1(\reg_inst.genblk1[3].SH.sr [7]),
    .S(wr_en),
    .X(_040_)
  );
  sky130_fd_sc_hd__mux2_1 _169_ (
    .A0(\reg_inst.genblk1[3].SH.sr [9]),
    .A1(\reg_inst.genblk1[3].SH.sr [8]),
    .S(wr_en),
    .X(_041_)
  );
  sky130_fd_sc_hd__mux2_1 _170_ (
    .A0(\reg_inst.genblk1[3].SH.sr [10]),
    .A1(\reg_inst.genblk1[3].SH.sr [9]),
    .S(wr_en),
    .X(_042_)
  );
  sky130_fd_sc_hd__mux2_1 _171_ (
    .A0(\reg_inst.genblk1[3].SH.sr [11]),
    .A1(\reg_inst.genblk1[3].SH.sr [10]),
    .S(wr_en),
    .X(_043_)
  );
  sky130_fd_sc_hd__mux2_1 _172_ (
    .A0(\reg_inst.genblk1[3].SH.sr [12]),
    .A1(\reg_inst.genblk1[3].SH.sr [11]),
    .S(wr_en),
    .X(_044_)
  );
  sky130_fd_sc_hd__mux2_1 _173_ (
    .A0(\reg_inst.genblk1[3].SH.sr [13]),
    .A1(\reg_inst.genblk1[3].SH.sr [12]),
    .S(wr_en),
    .X(_045_)
  );
  sky130_fd_sc_hd__mux2_1 _174_ (
    .A0(\reg_inst.genblk1[3].SH.sr [14]),
    .A1(\reg_inst.genblk1[3].SH.sr [13]),
    .S(wr_en),
    .X(_046_)
  );
  sky130_fd_sc_hd__mux2_1 _175_ (
    .A0(\reg_inst.genblk1[3].SH.sr [15]),
    .A1(\reg_inst.genblk1[3].SH.sr [14]),
    .S(wr_en),
    .X(_047_)
  );
  sky130_fd_sc_hd__mux2_1 _176_ (
    .A0(\reg_inst.genblk1[0].SH.sr [0]),
    .A1(in0),
    .S(wr_en),
    .X(_048_)
  );
  sky130_fd_sc_hd__mux2_1 _177_ (
    .A0(\reg_inst.genblk1[0].SH.sr [1]),
    .A1(\reg_inst.genblk1[0].SH.sr [0]),
    .S(wr_en),
    .X(_049_)
  );
  sky130_fd_sc_hd__mux2_1 _178_ (
    .A0(\reg_inst.genblk1[0].SH.sr [2]),
    .A1(\reg_inst.genblk1[0].SH.sr [1]),
    .S(wr_en),
    .X(_050_)
  );
  sky130_fd_sc_hd__mux2_1 _179_ (
    .A0(\reg_inst.genblk1[0].SH.sr [3]),
    .A1(\reg_inst.genblk1[0].SH.sr [2]),
    .S(wr_en),
    .X(_051_)
  );
  sky130_fd_sc_hd__mux2_1 _180_ (
    .A0(\reg_inst.genblk1[0].SH.sr [4]),
    .A1(\reg_inst.genblk1[0].SH.sr [3]),
    .S(wr_en),
    .X(_052_)
  );
  sky130_fd_sc_hd__mux2_1 _181_ (
    .A0(\reg_inst.genblk1[0].SH.sr [5]),
    .A1(\reg_inst.genblk1[0].SH.sr [4]),
    .S(wr_en),
    .X(_053_)
  );
  sky130_fd_sc_hd__mux2_1 _182_ (
    .A0(\reg_inst.genblk1[0].SH.sr [6]),
    .A1(\reg_inst.genblk1[0].SH.sr [5]),
    .S(wr_en),
    .X(_054_)
  );
  sky130_fd_sc_hd__mux2_1 _183_ (
    .A0(\reg_inst.genblk1[0].SH.sr [7]),
    .A1(\reg_inst.genblk1[0].SH.sr [6]),
    .S(wr_en),
    .X(_055_)
  );
  sky130_fd_sc_hd__mux2_1 _184_ (
    .A0(\reg_inst.genblk1[0].SH.sr [8]),
    .A1(\reg_inst.genblk1[0].SH.sr [7]),
    .S(wr_en),
    .X(_056_)
  );
  sky130_fd_sc_hd__mux2_1 _185_ (
    .A0(\reg_inst.genblk1[0].SH.sr [9]),
    .A1(\reg_inst.genblk1[0].SH.sr [8]),
    .S(wr_en),
    .X(_057_)
  );
  sky130_fd_sc_hd__mux2_1 _186_ (
    .A0(\reg_inst.genblk1[0].SH.sr [10]),
    .A1(\reg_inst.genblk1[0].SH.sr [9]),
    .S(wr_en),
    .X(_058_)
  );
  sky130_fd_sc_hd__mux2_1 _187_ (
    .A0(\reg_inst.genblk1[0].SH.sr [11]),
    .A1(\reg_inst.genblk1[0].SH.sr [10]),
    .S(wr_en),
    .X(_059_)
  );
  sky130_fd_sc_hd__mux2_1 _188_ (
    .A0(\reg_inst.genblk1[0].SH.sr [12]),
    .A1(\reg_inst.genblk1[0].SH.sr [11]),
    .S(wr_en),
    .X(_060_)
  );
  sky130_fd_sc_hd__mux2_1 _189_ (
    .A0(\reg_inst.genblk1[0].SH.sr [13]),
    .A1(\reg_inst.genblk1[0].SH.sr [12]),
    .S(wr_en),
    .X(_061_)
  );
  sky130_fd_sc_hd__mux2_1 _190_ (
    .A0(\reg_inst.genblk1[0].SH.sr [14]),
    .A1(\reg_inst.genblk1[0].SH.sr [13]),
    .S(wr_en),
    .X(_062_)
  );
  sky130_fd_sc_hd__mux2_1 _191_ (
    .A0(\reg_inst.genblk1[0].SH.sr [15]),
    .A1(\reg_inst.genblk1[0].SH.sr [14]),
    .S(wr_en),
    .X(_063_)
  );
  sky130_fd_sc_hd__dfrtp_1 _192_ (
    .CLK(clk),
    .D(\dmux_inst.ff_out ),
    .Q(\ff_inst.out_ff ),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _193_ (
    .CLK(clk),
    .D(_000_),
    .Q(\reg_inst.genblk1[2].SH.sr [0]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _194_ (
    .CLK(clk),
    .D(_001_),
    .Q(\reg_inst.genblk1[2].SH.sr [1]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _195_ (
    .CLK(clk),
    .D(_002_),
    .Q(\reg_inst.genblk1[2].SH.sr [2]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _196_ (
    .CLK(clk),
    .D(_003_),
    .Q(\reg_inst.genblk1[2].SH.sr [3]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _197_ (
    .CLK(clk),
    .D(_004_),
    .Q(\reg_inst.genblk1[2].SH.sr [4]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _198_ (
    .CLK(clk),
    .D(_005_),
    .Q(\reg_inst.genblk1[2].SH.sr [5]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _199_ (
    .CLK(clk),
    .D(_006_),
    .Q(\reg_inst.genblk1[2].SH.sr [6]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _200_ (
    .CLK(clk),
    .D(_007_),
    .Q(\reg_inst.genblk1[2].SH.sr [7]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _201_ (
    .CLK(clk),
    .D(_008_),
    .Q(\reg_inst.genblk1[2].SH.sr [8]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _202_ (
    .CLK(clk),
    .D(_009_),
    .Q(\reg_inst.genblk1[2].SH.sr [9]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _203_ (
    .CLK(clk),
    .D(_010_),
    .Q(\reg_inst.genblk1[2].SH.sr [10]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _204_ (
    .CLK(clk),
    .D(_011_),
    .Q(\reg_inst.genblk1[2].SH.sr [11]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _205_ (
    .CLK(clk),
    .D(_012_),
    .Q(\reg_inst.genblk1[2].SH.sr [12]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _206_ (
    .CLK(clk),
    .D(_013_),
    .Q(\reg_inst.genblk1[2].SH.sr [13]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _207_ (
    .CLK(clk),
    .D(_014_),
    .Q(\reg_inst.genblk1[2].SH.sr [14]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _208_ (
    .CLK(clk),
    .D(_015_),
    .Q(\reg_inst.genblk1[2].SH.sr [15]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _209_ (
    .CLK(clk),
    .D(_016_),
    .Q(\reg_inst.genblk1[1].SH.sr [0]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _210_ (
    .CLK(clk),
    .D(_017_),
    .Q(\reg_inst.genblk1[1].SH.sr [1]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _211_ (
    .CLK(clk),
    .D(_018_),
    .Q(\reg_inst.genblk1[1].SH.sr [2]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _212_ (
    .CLK(clk),
    .D(_019_),
    .Q(\reg_inst.genblk1[1].SH.sr [3]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _213_ (
    .CLK(clk),
    .D(_020_),
    .Q(\reg_inst.genblk1[1].SH.sr [4]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _214_ (
    .CLK(clk),
    .D(_021_),
    .Q(\reg_inst.genblk1[1].SH.sr [5]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _215_ (
    .CLK(clk),
    .D(_022_),
    .Q(\reg_inst.genblk1[1].SH.sr [6]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _216_ (
    .CLK(clk),
    .D(_023_),
    .Q(\reg_inst.genblk1[1].SH.sr [7]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _217_ (
    .CLK(clk),
    .D(_024_),
    .Q(\reg_inst.genblk1[1].SH.sr [8]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _218_ (
    .CLK(clk),
    .D(_025_),
    .Q(\reg_inst.genblk1[1].SH.sr [9]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _219_ (
    .CLK(clk),
    .D(_026_),
    .Q(\reg_inst.genblk1[1].SH.sr [10]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _220_ (
    .CLK(clk),
    .D(_027_),
    .Q(\reg_inst.genblk1[1].SH.sr [11]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _221_ (
    .CLK(clk),
    .D(_028_),
    .Q(\reg_inst.genblk1[1].SH.sr [12]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _222_ (
    .CLK(clk),
    .D(_029_),
    .Q(\reg_inst.genblk1[1].SH.sr [13]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _223_ (
    .CLK(clk),
    .D(_030_),
    .Q(\reg_inst.genblk1[1].SH.sr [14]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _224_ (
    .CLK(clk),
    .D(_031_),
    .Q(\reg_inst.genblk1[1].SH.sr [15]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _225_ (
    .CLK(clk),
    .D(input_combination[0]),
    .Q(\ff_inst2.out_ff [0]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _226_ (
    .CLK(clk),
    .D(input_combination[1]),
    .Q(\ff_inst2.out_ff [1]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _227_ (
    .CLK(clk),
    .D(input_combination[2]),
    .Q(\ff_inst2.out_ff [2]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _228_ (
    .CLK(clk),
    .D(input_combination[3]),
    .Q(\ff_inst2.out_ff [3]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _229_ (
    .CLK(clk),
    .D(_032_),
    .Q(\reg_inst.genblk1[3].SH.sr [0]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _230_ (
    .CLK(clk),
    .D(_033_),
    .Q(\reg_inst.genblk1[3].SH.sr [1]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _231_ (
    .CLK(clk),
    .D(_034_),
    .Q(\reg_inst.genblk1[3].SH.sr [2]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _232_ (
    .CLK(clk),
    .D(_035_),
    .Q(\reg_inst.genblk1[3].SH.sr [3]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _233_ (
    .CLK(clk),
    .D(_036_),
    .Q(\reg_inst.genblk1[3].SH.sr [4]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _234_ (
    .CLK(clk),
    .D(_037_),
    .Q(\reg_inst.genblk1[3].SH.sr [5]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _235_ (
    .CLK(clk),
    .D(_038_),
    .Q(\reg_inst.genblk1[3].SH.sr [6]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _236_ (
    .CLK(clk),
    .D(_039_),
    .Q(\reg_inst.genblk1[3].SH.sr [7]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _237_ (
    .CLK(clk),
    .D(_040_),
    .Q(\reg_inst.genblk1[3].SH.sr [8]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _238_ (
    .CLK(clk),
    .D(_041_),
    .Q(\reg_inst.genblk1[3].SH.sr [9]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _239_ (
    .CLK(clk),
    .D(_042_),
    .Q(\reg_inst.genblk1[3].SH.sr [10]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _240_ (
    .CLK(clk),
    .D(_043_),
    .Q(\reg_inst.genblk1[3].SH.sr [11]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _241_ (
    .CLK(clk),
    .D(_044_),
    .Q(\reg_inst.genblk1[3].SH.sr [12]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _242_ (
    .CLK(clk),
    .D(_045_),
    .Q(\reg_inst.genblk1[3].SH.sr [13]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _243_ (
    .CLK(clk),
    .D(_046_),
    .Q(\reg_inst.genblk1[3].SH.sr [14]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _244_ (
    .CLK(clk),
    .D(_047_),
    .Q(\reg_inst.genblk1[3].SH.sr [15]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _245_ (
    .CLK(clk),
    .D(is_synced),
    .Q(\ff_inst3.out_ff ),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _246_ (
    .CLK(clk),
    .D(f_sel[0]),
    .Q(\ff_inst4.out_ff [0]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _247_ (
    .CLK(clk),
    .D(f_sel[1]),
    .Q(\ff_inst4.out_ff [1]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _248_ (
    .CLK(clk),
    .D(_048_),
    .Q(\reg_inst.genblk1[0].SH.sr [0]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _249_ (
    .CLK(clk),
    .D(_049_),
    .Q(\reg_inst.genblk1[0].SH.sr [1]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _250_ (
    .CLK(clk),
    .D(_050_),
    .Q(\reg_inst.genblk1[0].SH.sr [2]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _251_ (
    .CLK(clk),
    .D(_051_),
    .Q(\reg_inst.genblk1[0].SH.sr [3]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _252_ (
    .CLK(clk),
    .D(_052_),
    .Q(\reg_inst.genblk1[0].SH.sr [4]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _253_ (
    .CLK(clk),
    .D(_053_),
    .Q(\reg_inst.genblk1[0].SH.sr [5]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _254_ (
    .CLK(clk),
    .D(_054_),
    .Q(\reg_inst.genblk1[0].SH.sr [6]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _255_ (
    .CLK(clk),
    .D(_055_),
    .Q(\reg_inst.genblk1[0].SH.sr [7]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _256_ (
    .CLK(clk),
    .D(_056_),
    .Q(\reg_inst.genblk1[0].SH.sr [8]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _257_ (
    .CLK(clk),
    .D(_057_),
    .Q(\reg_inst.genblk1[0].SH.sr [9]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _258_ (
    .CLK(clk),
    .D(_058_),
    .Q(\reg_inst.genblk1[0].SH.sr [10]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _259_ (
    .CLK(clk),
    .D(_059_),
    .Q(\reg_inst.genblk1[0].SH.sr [11]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _260_ (
    .CLK(clk),
    .D(_060_),
    .Q(\reg_inst.genblk1[0].SH.sr [12]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _261_ (
    .CLK(clk),
    .D(_061_),
    .Q(\reg_inst.genblk1[0].SH.sr [13]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _262_ (
    .CLK(clk),
    .D(_062_),
    .Q(\reg_inst.genblk1[0].SH.sr [14]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _263_ (
    .CLK(clk),
    .D(_063_),
    .Q(\reg_inst.genblk1[0].SH.sr [15]),
    .RESET_B(rst)
  );
  assign D = \dmux_inst.ff_out ;
  assign \dmux_inst.is_synced  = \ff_inst3.out_ff ;
  assign \dmux_inst.out  = out;
  assign f_sel_reg = \ff_inst4.out_ff ;
  assign \ff_inst.D  = \dmux_inst.ff_out ;
  assign \ff_inst.clk  = clk;
  assign \ff_inst.rst  = rst;
  assign \ff_inst2.D  = input_combination;
  assign \ff_inst2.clk  = clk;
  assign \ff_inst2.rst  = rst;
  assign \ff_inst3.D  = is_synced;
  assign \ff_inst3.clk  = clk;
  assign \ff_inst3.rst  = rst;
  assign \ff_inst4.D  = f_sel;
  assign \ff_inst4.clk  = clk;
  assign \ff_inst4.rst  = rst;
  assign input_combination_reg = \ff_inst2.out_ff ;
  assign is_synced_reg = \ff_inst3.out_ff ;
  assign \mux_inst.f_sel  = \ff_inst4.out_ff ;
  assign out_ff = \ff_inst.out_ff ;
  assign \reg_inst.clk  = clk;
  assign \reg_inst.genblk1[0].SH.clk  = clk;
  assign \reg_inst.genblk1[0].SH.rst  = rst;
  assign \reg_inst.genblk1[0].SH.sel  = \ff_inst2.out_ff ;
  assign \reg_inst.genblk1[0].SH.serial_in  = in0;
  assign \reg_inst.genblk1[0].SH.wr_en  = wr_en;
  assign \reg_inst.genblk1[1].SH.clk  = clk;
  assign \reg_inst.genblk1[1].SH.rst  = rst;
  assign \reg_inst.genblk1[1].SH.sel  = \ff_inst2.out_ff ;
  assign \reg_inst.genblk1[1].SH.serial_in  = in1;
  assign \reg_inst.genblk1[1].SH.wr_en  = wr_en;
  assign \reg_inst.genblk1[2].SH.clk  = clk;
  assign \reg_inst.genblk1[2].SH.rst  = rst;
  assign \reg_inst.genblk1[2].SH.sel  = \ff_inst2.out_ff ;
  assign \reg_inst.genblk1[2].SH.serial_in  = in2;
  assign \reg_inst.genblk1[2].SH.wr_en  = wr_en;
  assign \reg_inst.genblk1[3].SH.clk  = clk;
  assign \reg_inst.genblk1[3].SH.rst  = rst;
  assign \reg_inst.genblk1[3].SH.sel  = \ff_inst2.out_ff ;
  assign \reg_inst.genblk1[3].SH.serial_in  = in3;
  assign \reg_inst.genblk1[3].SH.wr_en  = wr_en;
  assign \reg_inst.in0  = in0;
  assign \reg_inst.in1  = in1;
  assign \reg_inst.in2  = in2;
  assign \reg_inst.in3  = in3;
  assign \reg_inst.in_array  = { in3, in2, in1, in0 };
  assign \reg_inst.input_combination  = \ff_inst2.out_ff ;
  assign \reg_inst.rst  = rst;
  assign \reg_inst.wr_en  = wr_en;
endmodule
